### ISSUE TITLE
Not an issue, but a suggestion :)

### ISSUE THREAD

**Issue by simplyNoOne** [Nartynka/zlecenie-dla-wspanialego-woznego#4]
I was thinking that the janitor would want to have his notes sorted by rooms they refer to; 
It's just so much easier to look at a note and think "ok, so I have 3 tasks to do in the kitchen", than to search through the entire list and go "where the hell are all the notes refering to the kitchen?".
As I said, not an issue, just a suggestion that would improve (IMO) user experience.
Love the colours tho <3

![Screenshot 2022-02-16 140345](https://user-images.githubusercontent.com/82574004/154270268-16ffdf36-ee9b-4d34-8158-10f9beb52f74.png)

**Comment by Nartynka** [comment]
Love your suggestion <3. I definitely add this on the next sprint <3

**Comment by Nartynka** [comment]
Done in last commit
